# Generated by Django 4.1.3 on 2022-11-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
