# Generated by Django 4.1.3 on 2022-11-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_event_date_event_end_date_event_reg_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/profile.png', upload_to=''),
        ),
    ]
